name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout sources
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v3
      id: go
      with:
        go-version: 1.19

    - name: verify modules
      run: |
        go version
        go mod verify

    - name: set release version env var
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: build (linux)
      run: |
        make all

    - name: build (win)
      run: |
        make win

    - name: fix build artifacts
      run: |
        hack/make-release-binaries.sh ${{ env.RELEASE_VERSION }}

    - name: compute signature
      run: |
        hack/make-release-checksum.sh ${{ env.RELEASE_VERSION }}

    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "SHA256SUMS,client-v*-linux-amd64.gz,client-v*-win-amd64.gz,fakeserver-v*-linux-amd64.gz,fakeserver-v*-win-amd64.gz"
        token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
